from __future__ import annotations

from typing import Any

from .system import SpinSystem, InterfaceDevice


class DeviceEventHandler: ...


class ImageEventHandler: ...


class CameraList:
    system: SpinSystem

    @staticmethod
    def create_from_system(system: SpinSystem, update_interfaces: bool = ..., update_cams: bool = ...) -> CameraList: ...
    @staticmethod
    def create_from_interface(interface: InterfaceDevice, update_cams: bool = ...) -> CameraList: ...
    def get_size(self) -> Any: ...
    def create_camera_by_index(self, index: int) -> Camera: ...
    def remove_camera_by_index(self, index: int) -> None: ...
    def create_camera_by_serial(self, serial: str) -> Camera: ...
    def remove_camera_by_serial(self, serial: str) -> None: ...
    def create_camera_by_dev_id(self, dev_id: str) -> Camera: ...
    def remove_camera_by_dev_id(self, dev_id: str) -> None: ...
    def extend_camera_list(self, other_list: CameraList) -> None: ...


class Camera:
    camera_nodes: Any
    tl_dev_nodes: Any
    tl_stream_nodes: Any

    def release(self) -> None: ...
    def init_cam(self) -> None: ...
    def deinit_cam(self) -> None: ...
    def get_access_mode(self) -> Any: ...
    def read_port(self, address: int, num_bytes: int) -> bytes: ...
    def write_port(self, address: int, data: memoryview) -> None: ...
    def begin_acquisition(self) -> None: ...
    def end_acquisition(self) -> None: ...
    def attach_device_event_handler(self, callback: Any, name: str = ...) -> DeviceEventHandler: ...
    def detach_device_event_handler(self, handler: DeviceEventHandler) -> None: ...
    def attach_image_event_handler(self, callback: Any) -> ImageEventHandler: ...
    def detach_image_event_handler(self, handler: ImageEventHandler) -> None: ...
    def get_buffer_ownership(self) -> Any: ...
    def set_buffer_ownership(self, ownership: str) -> None: ...
    def get_buffer_count(self) -> Any: ...
    def get_buffer_size(self) -> Any: ...
    def get_buffer_total_size(self) -> Any: ...
    def set_user_buffer(self, buffer: Any) -> None: ...
    def set_user_buffers(self, buffers: Any, buffer_size: int) -> None: ...
    def get_unique_id(self) -> str: ...
    def is_streaming(self) -> bool: ...
    def get_gui_xml(self) -> str: ...
    def is_valid(self) -> bool: ...
    def is_init(self) -> bool: ...
    def get_max_packet_size(self) -> Any: ...
    def get_num_images_in_use(self) -> Any: ...
    def get_num_data_streams(self) -> Any: ...
    def force_ip(self) -> None: ...
    def get_next_image(self, timeout: Any = ..., stream_id: int = ...) -> Any: ...
    def get_node_map(self) -> Any: ...
    def get_tl_dev_node_map(self) -> Any: ...
    def get_tl_stream_node_map(self) -> Any: ...
