from __future__ import annotations

from typing import Any


class EventHandlerBase:
    ...


class LoggingEventHandler(EventHandlerBase):
    ...


class SystemEventHandler(EventHandlerBase):
    ...


class InterfaceEventHandler(EventHandlerBase):
    ...


class SpinSystem:
    system_nodes: Any

    def __init__(self) -> None: ...
    def set_logging_level(self, level: str) -> None: ...
    def get_logging_level(self) -> Any: ...
    def detach_all_log_handlers(self) -> None: ...
    def get_in_use(self) -> Any: ...
    def get_library_version(self) -> Any: ...
    def get_tl_node_map(self) -> Any: ...
    def attach_event_handler(self, callback_arrival: Any = ..., callback_removal: Any = ...) -> SystemEventHandler: ...
    def detach_event_handler(self, handler: SystemEventHandler) -> None: ...
    def attach_interface_event_handler(self, callback_arrival: Any = ..., callback_removal: Any = ..., update: bool = ...) -> InterfaceEventHandler: ...
    def detach_interface_event_handler(self, handler: InterfaceEventHandler) -> None: ...
    def attach_log_event_handler(self, callback: Any) -> LoggingEventHandler: ...
    def detach_log_event_handler(self, handler: LoggingEventHandler) -> None: ...
    def send_command(self, device_key: int, group_key: int, group_mask: int, action_time: int = ..., num_results: int = ...) -> Any: ...
    def create_interface_list(self, update_interfaces: bool = ...) -> Any: ...
    def update_interface_list(self) -> None: ...
    def update_camera_list(self, update_interfaces: bool = ...) -> Any: ...


class InterfaceDeviceList:
    system: SpinSystem

    def get_size(self) -> Any: ...
    def create_interface(self, index: int) -> Any: ...
    def extend(self, other: InterfaceDeviceList) -> None: ...


class InterfaceDevice:
    interface_nodes: Any

    def release(self) -> None: ...
    def attach_event_handler(self, callback_arrival: Any = ..., callback_removal: Any = ...) -> InterfaceEventHandler: ...
    def detach_event_handler(self, handler: InterfaceEventHandler) -> None: ...
    def get_in_use(self) -> Any: ...
    def send_command(self, device_key: int, group_key: int, group_mask: int, action_time: int = ..., num_results: int = ...) -> Any: ...
    def get_is_valid(self) -> Any: ...
    def update_camera_list(self) -> None: ...
    def get_tl_node_map(self) -> Any: ...
