"""Sphinx configuration for the pytweezer documentation.

Build locally with ``make html`` in this directory; the API reference under
``api/`` is regenerated by ``sphinx-apidoc`` each build and is not checked in.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

project = "pytweezer"
author = "The pytweezer contributors"
copyright = f"2026, {author}"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

language = "en"
exclude_patterns = ["_build", "notes/*", "Thumbs.db", ".DS_Store"]

html_theme = "furo"
html_static_path = ["_static"]

# Hardware / GPU / .NET libraries that are absent on a plain dev machine. autodoc
# imports each module to read its docstrings, so these are faked. Add to this
# list if a build reports "autodoc: failed to import".
autodoc_mock_imports = [
    "pylablib",
    "clr",
    "System",
    "cupy",
    "nidaqmx",
    "imutils",
    "pycaf",
    "easypyspin",
    "simple_pyspin",
    "PySpin",
    "nicelib",
]

autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
}
autodoc_typehints = "description"
autosummary_generate = True

napoleon_google_docstring = True
napoleon_numpy_docstring = True

myst_enable_extensions = ["colon_fence"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}
